version: '3'
  services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - "4000:4000"
    volumes:
      - ./:/var/app
      - deps:/var/app/deps
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: txtt_dev
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  deps:
